# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeMe
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    
  berichtbotnet:
    image: ghcr.io/hendrik1337/berichtbotnet:master
    restart: unless-stopped
    environment:
      DiscordToken: Your_Discord_Token
      PostgreSQLBerichtBotConnection: Host=db;Database=postgres;Username=postgres;Password=changeMe
    depends_on: 
      - db
  
  berichtsheftcreator:
    image: berichtsheftcreator
    build:
      context: .
      dockerfile: BerichtsheftCreator/Dockerfile
    environment:
      crawlerUrl: 
      nextcloudUrl: 
      username: 
      password: 
      remotePath: 
    volumes:
      - C:\Users\Hendrik\Documents\Docker\BerichtBot\Berichtshefte:/app/Berichtshefte
    ports:
      - "8002:8080"
      - "8003:8081"

volumes:
  db:

  
