# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeMe
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    
  berichtbotnet:
    image: ghcr.io/hendrik1337/berichtbotnet:master
    restart: "no"
    environment:
      DiscordToken: Your_Discord_Token
      PostgreSQLBerichtBotConnection: Host=db;Database=postgres;Username=postgres;Password=changeMe
    depends_on: 
      - db

volumes:
  db:
