# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: changeMe
    volumes:
      - db:/var/lib/postgresql/data
    
  berichtbotnet:
    build:
      dockerfile: BerichtBotNet/Dockerfile
    restart: unless-stopped 
    environment:
      DiscordToken: Your_Discord_Token
      PostgreSQLBerichtBotConnection: Host=db;Database=postgres;Username=postgres;Password=changeMe
    depends_on: 
      - db

volumes:
  db: